server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prison_visit_booker_registry
    username: prison_visit_booker_registry
    password: prison_visit_booker_registry

hmpps.auth.url: http://localhost:8090/auth
