server:
  port: 8083
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/prison_visit_booker_registry
    username: prison_visit_booker_registry
    password: prison_visit_booker_registry

hmpps.auth.url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
